export const FEATHER_ICONS_LIST: string[] = [
    'icon-activity', 'icon-airplay', 'icon-alert-circle', 'icon-alert-octagon', 'icon-alert-triangle',
    'icon-align-center', 'icon-align-justify', 'icon-align-left', 'icon-align-right', 'icon-anchor',
    'icon-aperture', 'icon-archive', 'icon-arrow-down-circle', 'icon-arrow-down-left', 'icon-arrow-down-right',
    'icon-arrow-down', 'icon-arrow-left-circle', 'icon-arrow-left', 'icon-arrow-right-circle', 'icon-arrow-right',
    'icon-arrow-up-circle', 'icon-arrow-up-left', 'icon-arrow-up-right', 'icon-arrow-up', 'icon-at-sign',
    'icon-award', 'icon-bar-chart-2', 'icon-bar-chart', 'icon-battery-charging', 'icon-battery',
    'icon-bell-off', 'icon-bell', 'icon-bluetooth', 'icon-bold', 'icon-book-open', 'icon-book',
    'icon-bookmark', 'icon-box', 'icon-briefcase', 'icon-calendar', 'icon-camera-off', 'icon-camera',
    'icon-cast', 'icon-check-circle', 'icon-check-square', 'icon-check', 'icon-chevron-down', 'icon-chevron-left',
    'icon-chevron-right', 'icon-chevron-up', 'icon-chevrons-down', 'icon-chevrons-left', 'icon-chevrons-right',
    'icon-chevrons-up', 'icon-chrome', 'icon-circle', 'icon-clipboard', 'icon-clock', 'icon-cloud-drizzle',
    'icon-cloud-lightning', 'icon-cloud-off', 'icon-cloud-rain', 'icon-cloud-snow', 'icon-cloud', 'icon-code',
    'icon-codepen', 'icon-codesandbox', 'icon-coffee', 'icon-columns', 'icon-command', 'icon-compass',
    'icon-copy', 'icon-corner-down-left', 'icon-corner-down-right', 'icon-corner-left-down', 'icon-corner-left-up',
    'icon-corner-right-down', 'icon-corner-right-up', 'icon-corner-up-left', 'icon-corner-up-right', 'icon-cpu',
    'icon-credit-card', 'icon-crop', 'icon-crosshair', 'icon-database', 'icon-delete', 'icon-disc',
    'icon-divide-circle', 'icon-divide-square', 'icon-divide', 'icon-dollar-sign', 'icon-download-cloud',
    'icon-download', 'icon-dribbble', 'icon-droplet', 'icon-edit-2', 'icon-edit-3', 'icon-edit',
    'icon-external-link', 'icon-eye-off', 'icon-eye', 'icon-facebook', 'icon-fast-forward', 'icon-feather',
    'icon-figma', 'icon-file-minus', 'icon-file-plus', 'icon-file-text', 'icon-file', 'icon-film',
    'icon-filter', 'icon-flag', 'icon-folder-minus', 'icon-folder-plus', 'icon-folder', 'icon-framer',
    'icon-frown', 'icon-gift', 'icon-git-branch', 'icon-git-commit', 'icon-git-merge', 'icon-git-pull-request',
    'icon-github', 'icon-gitlab', 'icon-globe', 'icon-grid', 'icon-hard-drive', 'icon-hash',
    'icon-headphones', 'icon-heart', 'icon-help-circle', 'icon-hexagon', 'icon-home', 'icon-image',
    'icon-inbox', 'icon-info', 'icon-instagram', 'icon-italic', 'icon-key', 'icon-layers',
    'icon-layout', 'icon-life-buoy', 'icon-link-2', 'icon-link', 'icon-linkedin', 'icon-list',
    'icon-loader', 'icon-lock', 'icon-log-in', 'icon-log-out', 'icon-mail', 'icon-map-pin',
    'icon-map', 'icon-maximize-2', 'icon-maximize', 'icon-meh', 'icon-menu', 'icon-message-circle',
    'icon-message-square', 'icon-mic-off', 'icon-mic', 'icon-minimize-2', 'icon-minimize', 'icon-minus-circle',
    'icon-minus-square', 'icon-minus', 'icon-monitor', 'icon-moon', 'icon-more-horizontal', 'icon-more-vertical',
    'icon-mouse-pointer', 'icon-move', 'icon-music', 'icon-navigation-2', 'icon-navigation', 'icon-octagon',
    'icon-package', 'icon-paperclip', 'icon-pause-circle', 'icon-pause', 'icon-pen-tool', 'icon-percent',
    'icon-phone-call', 'icon-phone-forwarded', 'icon-phone-incoming', 'icon-phone-missed', 'icon-phone-off',
    'icon-phone-outgoing', 'icon-phone', 'icon-pie-chart', 'icon-play-circle', 'icon-play', 'icon-plus-circle',
    'icon-plus-square', 'icon-plus', 'icon-pocket', 'icon-power', 'icon-printer', 'icon-radio',
    'icon-refresh-ccw', 'icon-refresh-cw', 'icon-repeat', 'icon-rewind', 'icon-rotate-ccw', 'icon-rotate-cw',
    'icon-rss', 'icon-save', 'icon-scissors', 'icon-search', 'icon-send', 'icon-server',
    'icon-settings', 'icon-share-2', 'icon-share', 'icon-shield-off', 'icon-shield', 'icon-shopping-bag',
    'icon-shopping-cart', 'icon-shuffle', 'icon-sidebar', 'icon-skip-back', 'icon-skip-forward', 'icon-slack',
    'icon-slash', 'icon-sliders', 'icon-smartphone', 'icon-smile', 'icon-speaker', 'icon-square',
    'icon-star', 'icon-stop-circle', 'icon-sun', 'icon-sunrise', 'icon-sunset', 'icon-tablet',
    'icon-tag', 'icon-target', 'icon-terminal', 'icon-thermometer', 'icon-thumbs-down', 'icon-thumbs-up',
    'icon-toggle-left', 'icon-toggle-right', 'icon-tool', 'icon-trash-2', 'icon-trash', 'icon-trello',
    'icon-trending-down', 'icon-trending-up', 'icon-triangle', 'icon-truck', 'icon-tv', 'icon-twitch',
    'icon-twitter', 'icon-type', 'icon-umbrella', 'icon-underline', 'icon-unlock', 'icon-upload-cloud',
    'icon-upload', 'icon-user-check', 'icon-user-minus', 'icon-user-plus', 'icon-user-x', 'icon-user',
    'icon-users', 'icon-video-off', 'icon-video', 'icon-voicemail', 'icon-volume-1', 'icon-volume-2',
    'icon-volume-x', 'icon-volume', 'icon-watch', 'icon-wifi-off', 'icon-wifi', 'icon-wind',
    'icon-x-circle', 'icon-x-octagon', 'icon-x-square', 'icon-x', 'icon-youtube', 'icon-zap-off',
    'icon-zap', 'icon-zoom-in', 'icon-zoom-out'
];
