export class PTLPaquetesSCModel {
    constructor(
        public paqueteSCId?: number,
        public codigoSuscriptorPaquete?: string,
        public codigoSuscriptor?: string,
        public codigoPaquete?: string,
        public codigoTipoPaquete?: string,
        public codigoTipoPago?: string,
        public codigoLicencia?: string,
        public fechaInicio?: string,
        public fechaProximoPago?: string,
        public fechaRenovacion?: string,
        public numRenovaciones?: number,
        public estadoLicencia?: boolean,
        public codigoUsuarioCreacion?: string,
        public fechaCreacion?: string,
        public tipoPago?: string,
        public descripcionPaquete?: string,
        public precioPaquete?: number,
        public codigoTipo?: string,
        public nombreTipo?: string,
        public descuentoMeses?: number,
        public mesesCobertura?: number,
        public valorMes?: number,
        public valorPago?: number,
        public observaciones?: string,
        public _acciones?: any,
        public codigoUsuarioModificacion?: string,
        public fechaCancelacion?: string,
        public fechaProximoPagoDate?: string,
        public fechaModificacion?: string,
        public nomSuscriptor?: string,
        public nomPaquete?: string,
        public historiales?: any
    ) { }
}
